# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PrimeiroProjetoViewCode350BF' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PrimeiroProjetoViewCode350BF

pod 'SnapKit', '~> 5.0.0'
pod 'CPF-CNPJ-Validator'

end
